# Generated by Django 5.2.11 on 2026-03-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraMainTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done')], max_length=50)),
                ('created', models.DateField()),
                ('package', models.CharField(max_length=100)),
                ('process_required', models.JSONField()),
            ],
            options={
                'db_table': 'jira_main_ticket',
                'ordering': ['issue_key'],
            },
        ),
        migrations.CreateModel(
            name='JiraSubTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Blocked', 'Blocked')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('predefined_process', models.CharField(max_length=100)),
                ('parent_key', models.ForeignKey(db_column='parent_key', on_delete=django.db.models.deletion.CASCADE, related_name='sub_tickets', to='mock_jira.jiramainticket', to_field='issue_key')),
            ],
            options={
                'db_table': 'jira_sub_ticket',
                'ordering': ['parent_key', 'issue_key'],
            },
        ),
    ]
