# Generated by Django 5.2.11 on 2026-03-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_jira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiramainticket',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed')], default='Closed', max_length=50),
        ),
        migrations.AlterField(
            model_name='jirasubticket',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed')], default='Completed', max_length=50),
        ),
    ]
