# Generated by Django 5.2.11 on 2026-04-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_jira', '0002_alter_jiramainticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiramainticket',
            name='process_required',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='jirasubticket',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Completed', max_length=50),
        ),
    ]
