# Generated by Django 5.2.11 on 2026-05-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_jira', '0003_alter_jiramainticket_process_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiramainticket',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
