# Generated by Django 5.2.11 on 2026-05-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='total_skipped',
            field=models.IntegerField(default=0),
        ),
    ]
