# Generated by Django 5.2.11 on 2026-05-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_synclog_total_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawticket',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
