# Generated by Django 5.2.11 on 2026-06-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rawticket_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawticket',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='rawticket',
            name='resolved_date',
        ),
    ]
