# Generated by Django 5.2.11 on 2026-06-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_rawticket_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='total_processed_main',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='total_processed_sub',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='total_skipped_main',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='total_skipped_sub',
            field=models.IntegerField(default=0),
        ),
    ]
